apiVersion: apps/v1
kind: Deployment
metadata:
  name: "2048-deployment"
  labels:
    app: game
spec:
  selector:
    matchLabels:
      app: game
  replicas: 3
  template:
    metadata:
      labels:
        app: game
    spec:

      containers:
        - image: alexwhen/docker-2048
          imagePullPolicy: Always
          name: "2048"
          ports:
            - containerPort: 80
              protocol: TCP